### ISSUE TITLE
Possibility of sync version of `createSyncAccessHandle()`

### ISSUE THREAD

**Issue by tomayac** [whatwg/fs#100]
The current `createSyncAccessHandle()` method is asynchronous. Since we don’t universally have [JSPI](https://v8.dev/blog/jspi) on all platforms/browsers yet, obtaining a `FileSystemSyncAccessHandle` can be unergonomic from a Wasm context. We hear developer demand for a synchronous version of `createSyncAccessHandle()` (obviously tied to Worker contexts). Is this feasible?

**Comment by tomayac** [comment]
Right. I have created this new Issue because…

> If anyone else can provide a strong case to make createSyncAccessHandle sync and would like to drive that work, then of course they are welcome to

…we may have found this “anyone”. I hope for them to chime in on the Issue.

**Comment by d3lm** [comment]
Hello 👋 I am the Team Lead at StackBlitz for [WebContainer, a Node.js runtime for the browser](https://blog.stackblitz.com/posts/introducing-webcontainers/). For our runtime we would highly benefit from `createSyncAccessHandle` being synchronous because our idea is to use the OPFS as another layer in our kernel to allow swapping files out of memory onto disk which can drastically reduce the memory footprint for large applications. Our kernel is compiled to Wasm and a lot of APIs are expected to be synchronous. As Thomas said, without universal support for JSPI that allows to suspend the execution of the Wasm module when calling a function that returns a Promise, the only way we could open files from our kernel is to use a separate thread that performs this operation but that also means we'd have to write to that file on a separate thread (worker) IIUC (similar to how [WORKERFS](https://github.com/emscripten-core/emscripten/blob/main/system/lib/wasmfs/backends/opfs_backend.cpp) works for emscripten). In an ideal world, we could synchronously open files directly from our kernel, and start swapping the content.

Does that make sense?

**Comment by a-sully** [comment]
Hi @d3lm, thanks for contributing your use case! Just to make sure I understand correctly - you still would need to call the async `getFileHandle()` method (and maybe also `getDirectoryHandle()`) to get the `FileSystemFileHandle` on which you would then call `createSyncAccessHandle()`, correct?

On that earlier spec issue it was concluded that making `createSyncAccessHandle()` sync would not provide much benefit, in part because the async directory traversal methods that we never intend to make sync (i.e. `getFileHandle()` and `getDirectoryHandle()`) were assumed to be a prerequisite to open the file anyways. If you need to call these async methods anyways, then a sync `createSyncAccessHandle()` doesn't really help you much. This is the case for Emscripten, for example, which is general-purpose and performs this directory traversal on-demand.

The most convincing use case (courtesy of https://github.com/rhashimoto/wa-sqlite/discussions/67) I've seen so far for `createSyncAccessHandle()` to be sync is if there's a known set of files you plan to interact with. In this case, you could (asynchronously) get all the `FileSystemFileHandle`s you need up front, then read/write/etc all synchronously... at which point an async "open" method is a real hindrance

**Comment by d3lm** [comment]
@a-sully Yes, that is absolutely right. I'd still need to call `getDirectoryHandle` or `getFileHandle`. And if there won't be sync variants of those then yea it doesn't make much sense to make `createSyncAccessHandle` synchronous. I think for our use case we'd need basically the entire chain of API calls to be synchronous so we could use OPFS as a backing store for our file system.
