### ISSUE TITLE
query access for filehandles

### ISSUE THREAD

**Issue by jesup** [whatwg/fs#25]
The language for getting FileHandles indicates you check the 'query access' for the file using readwrite if create is true, and read if create is false.  (though it also says you don't need to implement this if you don't implement any dependent specs).

a) Does this mean you can't write to a file unless you pass create: true?
b) "not implementing any dependent specs" seems incredibly vague.   They should be called out directly, or even better yet it should indicate under what circumstances it's needed to check the 'query access' in more concrete form, and then this rule can be applied to any current or future dependent specs.

**Comment by a-sully** [comment]
> a) Does this mean you can't write to a file unless you pass create: true? 

No. The behavior here is (to my pleasant surprise) properly specified, though within the OPFS there's no way to actually get a handle that will return anything other than "granted"

The query access algorithm for the root of the OPFS, given [here](https://fs.spec.whatwg.org/#ref-for-entry-query-access%E2%91%A0%E2%93%AA), always returns "[granted](https://w3c.github.io/permissions/#dom-permissionstate-granted)". Then, creating a child file or directory [passes the query algorithm of the parent](https://fs.spec.whatwg.org/#ref-for-entry-query-access%E2%91%A3:~:text=Let%20child%20be%20a%20new%20file%20entry%20whose%20query%20access%20and%20request%20access%20algorithms%20are%20those%20of%20entry.).

> b) "not implementing any dependent specs" seems incredibly vague. They should be called out directly, or even better yet it should indicate under what circumstances it's needed to check the 'query access' in more concrete form, and then this rule can be applied to any current or future dependent specs.

I'm not seeing the "not implementing any dependent specs" language - perhaps it has since been taken out?

Closing this issue for now, but please re-open if there's more here worth discussing!
